using ArcGISProMCP.Core.Models;

namespace ArcGISProMCP.UnitTests;

/// <summary>
/// The approved production tool contract snapshot for the current implementation batch (239 tools since D-118).
/// This is intentionally a small contract snapshot, not a copy of every JSON Schema detail.
/// </summary>
internal sealed record ProductionToolContract(
    string Name,
    string Category,
    string ExecutionType,
    bool RequiresArcGIS);

internal static class ProductionToolContractSnapshot
{
    public static IReadOnlyList<ProductionToolContract> Tools { get; } =
    [
        new("add_field", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("add_layer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("add_layout_text", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("add_legend", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("add_north_arrow", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("add_scale_bar", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("alter_field", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("append_features", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("buffer", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("calculate_field", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("cell_statistics", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("check_extension", ToolCategories.System, ExecutionTypes.Native, true),
        new("clear_selection", ToolCategories.Selection, ExecutionTypes.Native, true),
        new("clip", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("copy_dataset", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("create_file_gdb", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("create_layout", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("create_map", ToolCategories.Map, ExecutionTypes.Native, true),
        new("create_selection_snapshot", ToolCategories.Selection, ExecutionTypes.Native, true),
        new("dataset_summary", ToolCategories.Python, ExecutionTypes.Python, false),
        new("delete_dataset", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("delete_features", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("describe_geoprocessing_tool", ToolCategories.Geoprocessing, ExecutionTypes.Native, true),
        new("discard_edits", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("dissolve", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("erase", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("export_layout_eps", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("export_layout_jpg", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("export_layout_pdf", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("export_layout_png", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("export_layout_svg", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("export_layout_tif", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("export_table", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("focal_statistics", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("get_arcgis_version", ToolCategories.General, ExecutionTypes.Native, false),
        new("get_audit_log", ToolCategories.System, ExecutionTypes.Native, true),
        new("get_current_map", ToolCategories.General, ExecutionTypes.Native, false),
        new("get_dataset_info", ToolCategories.Python, ExecutionTypes.Python, false),
        new("get_definition_query", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("get_domains", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("get_edit_session", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("get_feature_count", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("get_field_info", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("get_field_statistics", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("get_field_values", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("get_indexes", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("get_label_info", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("get_layer_features", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("get_layer_info", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("get_layer_symbology", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("get_layers", ToolCategories.General, ExecutionTypes.Native, false),
        new("get_layout_info", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("get_license_info", ToolCategories.General, ExecutionTypes.Native, false),
        new("get_map_extent", ToolCategories.Map, ExecutionTypes.Native, true),
        new("get_map_info", ToolCategories.Map, ExecutionTypes.Native, true),
        new("get_messages", ToolCategories.Geoprocessing, ExecutionTypes.Native, true),
        new("get_project_info", ToolCategories.General, ExecutionTypes.Native, false),
        new("get_raster_info", ToolCategories.Python, ExecutionTypes.Python, false),
        new("get_schema_info", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("get_selected_features", ToolCategories.Selection, ExecutionTypes.Native, true),
        new("get_subtypes", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("get_unique_values", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("get_workspace", ToolCategories.Project, ExecutionTypes.Native, false),
        new("insert_features", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("intersect", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("list_databases", ToolCategories.Project, ExecutionTypes.Native, true),
        new("list_fields", ToolCategories.Python, ExecutionTypes.Python, false),
        new("list_geoprocessing_tools", ToolCategories.Geoprocessing, ExecutionTypes.Native, true),
        new("list_layout_elements", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("list_layouts", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("list_maps", ToolCategories.Map, ExecutionTypes.Native, true),
        new("list_rasters", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("list_tables", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("list_workspace_datasets", ToolCategories.Python, ExecutionTypes.Python, false),
        new("merge", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("move_layer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("near", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("ping", ToolCategories.General, ExecutionTypes.Native, false),
        new("project", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("python_bridge_ping", ToolCategories.Python, ExecutionTypes.Python, false),
        new("python_runtime_info", ToolCategories.Python, ExecutionTypes.Python, false),
        new("query_attributes", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("raster_calc", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("raster_clip", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("raster_mosaic", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("raster_resample", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("raster_statistics", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("remove_layer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("rename_dataset", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("repair_geometry", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("restore_selection_snapshot", ToolCategories.Selection, ExecutionTypes.Native, true),
        new("run_geoprocessing", ToolCategories.Geoprocessing, ExecutionTypes.Geoprocessing, true),
        new("save_edits", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("save_project", ToolCategories.Project, ExecutionTypes.Native, true),
        new("select_by_attribute", ToolCategories.Selection, ExecutionTypes.Geoprocessing, true),
        new("select_by_location", ToolCategories.Selection, ExecutionTypes.Geoprocessing, true),
        new("select_layer", ToolCategories.Selection, ExecutionTypes.Native, true),
        new("set_definition_query", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("set_label_visibility", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("set_layer_visibility", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("set_map_extent", ToolCategories.Map, ExecutionTypes.Native, true),
        new("set_simple_symbology", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("set_workspace", ToolCategories.Project, ExecutionTypes.Native, false),
        new("spatial_join", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("summarize_features", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("set_layer_transparency", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("set_layer_scale_range", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("create_group_layer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("set_basemap", ToolCategories.Map, ExecutionTypes.Native, true),
        new("get_broken_layers", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("repair_layer_source", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("add_join", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("remove_join", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("rename_layer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("duplicate_layer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("set_layer_renderer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("list_color_ramps", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("apply_symbology_from_layer", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("save_layer_file", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("get_map_view", ToolCategories.Map, ExecutionTypes.Native, true),
        new("set_map_view", ToolCategories.Map, ExecutionTypes.Native, true),
        new("export_map_view", ToolCategories.Map, ExecutionTypes.Native, true),
        new("list_bookmarks", ToolCategories.Map, ExecutionTypes.Native, true),
        new("create_bookmark", ToolCategories.Map, ExecutionTypes.Native, true),
        new("apply_bookmark", ToolCategories.Map, ExecutionTypes.Native, true),
        new("delete_bookmark", ToolCategories.Map, ExecutionTypes.Native, true),
        new("union", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("update_features", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        // ── D-064 · 功能完善第四批（128 → 149）：schema 6 + project 5 + 数据发现 4 + 批处理 2 + G-166 差异化 4 ──
        new("create_feature_class", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("create_table", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("add_fields", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("delete_field", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("truncate_table", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("export_features", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("remove_map", ToolCategories.Project, ExecutionTypes.Native, true),
        new("activate_map", ToolCategories.Map, ExecutionTypes.Native, true),
        new("set_map_properties", ToolCategories.Map, ExecutionTypes.Native, true),
        new("get_environment", ToolCategories.Geoprocessing, ExecutionTypes.Native, true),
        new("set_environment", ToolCategories.Geoprocessing, ExecutionTypes.Native, true),
        new("search_data", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("list_folder", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("add_folder_connection", ToolCategories.Project, ExecutionTypes.Native, true),
        new("get_project_items", ToolCategories.Project, ExecutionTypes.Native, true),
        new("run_batch", ToolCategories.General, ExecutionTypes.Native, true),
        new("export_map_series", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("diagnose", ToolCategories.System, ExecutionTypes.Native, false),
        new("snapshot_project", ToolCategories.Project, ExecutionTypes.Native, true),
        new("restore_snapshot", ToolCategories.Project, ExecutionTypes.Native, true),
        new("set_readonly_mode", ToolCategories.System, ExecutionTypes.Native, false),
        // ── D-073 数据文件夹工作流（5 件）──
        new("scan_data_folder", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("load_folder_data", ToolCategories.Project, ExecutionTypes.Native, true),
        new("apply_processing_plan", ToolCategories.General, ExecutionTypes.Native, true),
        new("get_job_status", ToolCategories.System, ExecutionTypes.Native, false),
        new("get_job_report", ToolCategories.System, ExecutionTypes.Native, false),
        // ── D-084 M1 前置：B1 作业控制/检索（4）＋B2 度量/配置（6）──
        new("list_jobs", ToolCategories.System, ExecutionTypes.Native, false),
        new("cancel_job", ToolCategories.System, ExecutionTypes.Native, true),
        new("validate_plan", ToolCategories.General, ExecutionTypes.Native, true),
        new("describe_tool_catalog", ToolCategories.General, ExecutionTypes.Native, false),
        new("get_geometry_info", ToolCategories.Attribute, ExecutionTypes.Native, true),
        new("find_identical", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("generate_quality_report", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("set_layout_element_properties", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("set_label_properties", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("configure_map_series", ToolCategories.Layout, ExecutionTypes.Native, true),
        // ── D-086 B3/B4 非 PS 批二（6 件）──
        new("export_design_bundle", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("validate_design_bundle", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("refresh_design_bundle", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("validate_delivery_package", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("suggest_workflow", ToolCategories.General, ExecutionTypes.Native, false),
        new("get_performance_stats", ToolCategories.System, ExecutionTypes.Native, false),
        // ── D-088 M2 批一 P1/P2 质量与溯源（9 件全 Read）──
        new("validate_geometries", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("check_topology_rules", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("compare_datasets", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("compare_schemas", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("validate_field_constraints", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("inspect_raster_alignment", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("list_geographic_transformations", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("trace_dataset_dependencies", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("get_dataset_lineage", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        // ── D-092 M2 批二 P3/P4 域治理与数据管理（9W＋1R）──
        new("create_domain", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("update_domain", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("delete_domain", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("assign_domain_to_field", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("remove_domain_from_field", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("configure_subtypes", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("create_relationship_class", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("calculate_geometry_attributes", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("define_projection", ToolCategories.DataManagement, ExecutionTypes.Geoprocessing, true),
        new("validate_relationship_class", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        // ── D-094 M2 批三 P5 八件分析工具（全 W）──
        new("simplify_features", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("smooth_features", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("polygon_neighbors", ToolCategories.Analysis, ExecutionTypes.Native, true),
        new("generate_tessellation", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("calculate_service_areas", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("solve_routes", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("spatial_autocorrelation", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("hotspot_analysis", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        // ── D-096 M2 批四 P6 栅格族六件（1R＋5W）──
        new("raster_pixel_inspect", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("build_raster_pyramids", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("compose_raster_bands", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("raster_change_detection", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("raster_reproject", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        new("zonal_histogram", ToolCategories.Analysis, ExecutionTypes.Geoprocessing, true),
        // ── PS 通道（D-091 + D-102；D-102 生产注册 223，名册三层 285 恒定）──
        new("ps_apply_design_recipe", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_compare_document_versions", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_create_adjustment_layer", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_create_document_snapshot", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_export_deliverables", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_get_capabilities", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_get_document_info", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_get_layer_info", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_import_design_bundle", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_list_documents", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_list_layers", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_manage_artboards", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_place_design_asset", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_preview_document", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_refresh_design_bundle", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_restore_document_snapshot", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_set_layer_mask", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_set_layer_properties", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_set_text_properties", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        new("ps_validate_document", ToolCategories.Photoshop, ExecutionTypes.Bridge, false),
        // ── D-104 M4 首批：X15 点云只读检查（Native；LAS 1.2 PDRF 0 子集）──
        new("inspect_point_cloud", ToolCategories.Quality, ExecutionTypes.Native, true),
        // ── D-118 M4 Native 十五件（类别取值为 d118CategoryChoice；参数面＝冻结正本嵌入）──
        new("detect_temporal_change_points", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("compare_temporal_trajectories", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("export_time_animation", ToolCategories.Layout, ExecutionTypes.Native, true),
        new("extrude_scene_features", ToolCategories.Layer, ExecutionTypes.Native, true),
        new("create_elevation_profile", ToolCategories.Raster, ExecutionTypes.Native, true),
        new("export_scene_package", ToolCategories.Project, ExecutionTypes.Native, true),
        new("assess_remote_sensing_quality", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("assess_classification_accuracy", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("design_spatial_sample", ToolCategories.DataManagement, ExecutionTypes.Native, true),
        new("cross_validate_spatial_model", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("analyze_scenario_sensitivity", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("compare_multi_criteria_scenarios", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("evaluate_scenario_ensemble", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("validate_statistical_assumptions", ToolCategories.Quality, ExecutionTypes.Native, true),
        new("validate_interchange_conformance", ToolCategories.Quality, ExecutionTypes.Native, true),
        ];

    public static IReadOnlySet<string> ForbiddenToolNames { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
            "python_execute",
            "sleep_test",
            "raise_test_exception"
        };
}
