# D-060 - verify/generate SDK reference-set accounting (refset.props) and run deep verification.
# Deep checks: per-file SHA256, AssemblyVersion prefix, PublicKeyToken identity.
# Output: <RefsDir>/refset.props  +  report json (path via -ReportPath)
# Exit: 0 = PASS, 1 = FAIL
param(
  [string]$RefsDir = "D:\ArcGIS-Pro-MCP 2.0\sdk-refs\pro-13.0-net6",
  [string]$ExpectedPrefix = "13.0.",
  [string]$ExpectedToken = "8fc3cc631e44ad86",
  [string]$PackageVersion = "3.0.0.36056",
  [string]$ReportPath = "D:\ArcGIS-Pro-MCP 2.0\.runtime\evolution\phase15\run-20260919-d060\verify-sdk-refs.json"
)
$ErrorActionPreference = 'Stop'

# canonical order MUST match the <_ArcGISSdkRefRequired> item order in Directory.Build.targets
$rel = @(
  'ArcGIS.Core.dll',
  'ArcGIS.Desktop.Framework.dll',
  'Extensions\Core\ArcGIS.Desktop.Core.dll',
  'Extensions\Mapping\ArcGIS.Desktop.Mapping.dll',
  'Extensions\Catalog\ArcGIS.Desktop.Catalog.dll',
  'Extensions\Layout\ArcGIS.Desktop.Layouts.dll'
)

$fail = @()
$records = @()
foreach ($r in $rel) {
  $p = Join-Path $RefsDir $r
  if (-not (Test-Path -LiteralPath $p)) { $fail += "MISSING $r"; continue }
  $h = (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLower()
  $an = [System.Reflection.AssemblyName]::GetAssemblyName($p)
  $tokBytes = $an.GetPublicKeyToken()
  $tok = ($tokBytes | ForEach-Object { $_.ToString('x2') }) -join ''
  $verOk = $an.Version.ToString().StartsWith($ExpectedPrefix)
  $tokOk = ($tok -eq $ExpectedToken)
  if (-not $verOk) { $fail += "VERSION $r = $($an.Version)" }
  if (-not $tokOk) { $fail += "TOKEN $r = $tok" }
  $records += [pscustomobject]@{ rel = $r; full = $p; sha256 = $h; asmVersion = $an.Version.ToString(); token = $tok; versionOk = $verOk; tokenOk = $tokOk }
  "  {0,-52} ver={1,-12} tok={2,-18} sha={3}" -f $r, $an.Version, $tok, $h.Substring(0, 16)
}

$digest = ($records | ForEach-Object { $_.sha256 }) -join ';'
$verdict = 'PASS'
if ($fail.Count -gt 0) { $verdict = 'FAIL' }

# generate accounting file (only meaningful when all files present)
if ($fail.Count -eq 0) {
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine('<Project>')
  [void]$sb.AppendLine('  <!-- GENERATED by scripts/verify-sdk-refs.ps1 - do not hand-edit. -->')
  [void]$sb.AppendLine('  <PropertyGroup>')
  [void]$sb.AppendLine("    <ArcGISProSdkRefsVersionPrefix>$ExpectedPrefix</ArcGISProSdkRefsVersionPrefix>")
  [void]$sb.AppendLine("    <ArcGISProSdkRefsPublicKeyToken>$ExpectedToken</ArcGISProSdkRefsPublicKeyToken>")
  [void]$sb.AppendLine("    <ArcGISProSdkRefsPackageVersion>$PackageVersion</ArcGISProSdkRefsPackageVersion>")
  [void]$sb.AppendLine("    <ArcGISProSdkRefsDigest>$digest</ArcGISProSdkRefsDigest>")
  [void]$sb.AppendLine("    <ArcGISProSdkRefsGeneratedAt>$((Get-Date).ToString('s'))</ArcGISProSdkRefsGeneratedAt>")
  [void]$sb.AppendLine('  </PropertyGroup>')
  [void]$sb.AppendLine('  <ItemGroup>')
  foreach ($rec in $records) {
    [void]$sb.AppendLine("    <ArcGISSdkRefRecord Include=`"`$(ArcGISProSdkRefs)$($rec.rel)`" Sha256=`"$($rec.sha256)`" />")
  }
  [void]$sb.AppendLine('  </ItemGroup>')
  [void]$sb.AppendLine('</Project>')
  $propsPath = Join-Path $RefsDir 'refset.props'
  [System.IO.File]::WriteAllText($propsPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
  "refset.props written: $propsPath"
} else {
  "refset.props NOT written (verification failed)"
}

$report = [pscustomobject]@{
  generatedAt = (Get-Date).ToString('s'); refsDir = $RefsDir
  expectedPrefix = $ExpectedPrefix; expectedToken = $ExpectedToken; packageVersion = $PackageVersion
  digest = $digest; records = $records; failures = $fail; verdict = $verdict
}
$dir = Split-Path -Parent $ReportPath
if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
$report | ConvertTo-Json -Depth 6 | Out-File -LiteralPath $ReportPath -Encoding UTF8

""
if ($fail.Count -eq 0) { "failures = NONE" } else { "failures = " + ($fail -join ' | ') }
"digest = $digest"
"VERDICT = $verdict"
if ($verdict -ne 'PASS') { exit 1 }
