// <auto-generated by f2-impl/build_frozen_schema_embeddings_d118.py>
// D-118：15 件冻结 schema 正本（run-20260928-d082/f03b-5-schemas/*.schema.json）的文本嵌入。
// 目的＝输入面 ≡ 工单指定冻结 schema 逐字（G-275 R-1 契约预检 21/21 在场件中的本批 15 件），
// 参数面等值由构造保证：工具 InputSchema 由下列文本经 JSON 解析物化，不做人工转写。
// 归一口径（如实声明）：15 份正本均为 CRLF；嵌入文本＝正本去 BOM 并把 CRLF 归一为 LF 后的逐字节副本，
// 归一前后字节数与两种 SHA 见 f2-impl/embedding-ledger.json。嵌入正文整体缩进 8 空格以满足 C# raw string
// literal（CS8999），编译器按闭合定界符缩进剥离，故常量取值＝归一后的正本内容。
// SchemaSha256ByToolName ＝ 正本**原始字节** SHA-256（逐件实测 ≡ Benchmarks/m4-capability-surface-v1.jsonl 的 schemaSha256）；
// SchemaTextSha256ByToolName ＝ 嵌入文本（CRLF→LF 后）的 SHA-256。两者由测试分别对盘复核。
using System.Collections.Generic;

namespace ArcGISProMCP.Tools;

public static class D118FrozenSchemas
{
    /// <summary>detect_temporal_change_points · 冻结 schema 文本嵌入（正本原始 sha256 915F2628C86F）。</summary>
    public const string DetectTemporalChangePointsJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/detect_temporal_change_points.schema.json",
         "title": "detect_temporal_change_points",
         "type": "object",
         "properties": {
          "series": {
           "type": "string",
           "description": "时间序列表/要素（含时间与值字段）。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "valueField": {
           "type": "string",
           "description": "值字段（须带单位）。"
          },
          "method": {
           "type": "string",
           "description": "固定方法目录（不接受任意代码）。",
           "enum": [
            "pettitt",
            "cusum",
            "bayesian_online",
            "mann_kendall_segment"
           ]
          },
          "minSegmentLength": {
           "type": "integer",
           "default": 2,
           "description": "最小段长（样本数）。"
          },
          "significanceLevel": {
           "type": "number",
           "default": 0.05,
           "description": "显著性水平（须回显多重检验政策）。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "series",
          "outputPath",
          "valueField",
          "method"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X1",
          "catalogSection": "§4 X02",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": "[VERIFY] 方法实现归属（Native / 受控 Python / GP）未定；Python 通道只允许有类型操作。"
         }
        }
        """;

    public const string DetectTemporalChangePointsToolName = "detect_temporal_change_points";

    public const string DetectTemporalChangePointsSchemaSha256 = "915F2628C86F21831870BA0228591FCBDDD90FFCF6EE0C8C6B6F7BED4CC22B0C";

    public const string DetectTemporalChangePointsSchemaTextSha256 = "0A0AF02F6C070A4E64D9D92A222C4FA4EB9C9E533E84A87595F71FEC5058CE1A";

    /// <summary>compare_temporal_trajectories · 冻结 schema 文本嵌入（正本原始 sha256 CDD6CF5FFE08）。</summary>
    public const string CompareTemporalTrajectoriesJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/compare_temporal_trajectories.schema.json",
         "title": "compare_temporal_trajectories",
         "type": "object",
         "properties": {
          "series": {
           "type": "string",
           "description": "多区同量纲序列。"
          },
          "groupField": {
           "type": "string",
           "description": "分区/分组字段。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "alignment": {
           "type": "string",
           "description": "对齐政策。",
           "enum": [
            "none",
            "resample",
            "shift"
           ]
          },
          "normalization": {
           "type": "string",
           "description": "标准化。",
           "enum": [
            "none",
            "zscore",
            "minmax",
            "rank"
           ]
          },
          "missingPolicy": {
           "type": "string",
           "default": "drop",
           "description": "缺测政策。",
           "enum": [
            "drop",
            "interpolate",
            "zero"
           ]
          },
          "clusterCount": {
           "type": "integer",
           "default": 0,
           "description": "聚类数（0＝不聚类）。"
          },
          "seed": {
           "type": "integer",
           "default": 0,
           "description": "随机种子（缺省 0＝固定确定性种子）。0 表示“确定性默认”，不是“随机”。抽样/分类/聚类/情景/传播类工具必须可复现。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "series",
          "groupField",
          "outputPath",
          "alignment",
          "normalization"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X1",
          "catalogSection": "§4 X05",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string CompareTemporalTrajectoriesToolName = "compare_temporal_trajectories";

    public const string CompareTemporalTrajectoriesSchemaSha256 = "CDD6CF5FFE08F8CEA095DEEF55380A22AE67DE829DCB628C3A3523C68F14EB95";

    public const string CompareTemporalTrajectoriesSchemaTextSha256 = "7AB37E3BF55FC648E563C3F208F0835285F88E4D5F6848BDE52BC50EB2DF5C51";

    /// <summary>export_time_animation · 冻结 schema 文本嵌入（正本原始 sha256 25CD55F2F294）。</summary>
    public const string ExportTimeAnimationJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/export_time_animation.schema.json",
         "title": "export_time_animation",
         "type": "object",
         "properties": {
          "timeLayers": {
           "type": "array",
           "description": "参与动画的时间图层。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "visualRules": {
           "type": "object",
           "description": "固定视觉规则（分类/相机/时间戳格式）。"
          },
          "format": {
           "type": "string",
           "default": "gif",
           "description": "输出格式。",
           "enum": [
            "gif",
            "mp4",
            "frame_sequence"
           ]
          },
          "frameIntervalMs": {
           "type": "integer",
           "default": 500,
           "description": "帧间隔毫秒。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "timeLayers",
          "outputPath",
          "visualRules"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X1",
          "catalogSection": "§4 X06",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Layout",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": "[VERIFY] 编码器依赖（如 ffmpeg）未批准安装 ⇒ 依赖清单进 Spike 计划。"
         }
        }
        """;

    public const string ExportTimeAnimationToolName = "export_time_animation";

    public const string ExportTimeAnimationSchemaSha256 = "25CD55F2F2947ACB9ABCD83E0E667DEF7279C75D9981293DDB7E212EAC752EB4";

    public const string ExportTimeAnimationSchemaTextSha256 = "95DB13B981F0C89692C5AF8302A0FA490670FB805AFFBE6F4093F74FEC102DEB";

    /// <summary>extrude_scene_features · 冻结 schema 文本嵌入（正本原始 sha256 BBF9E4BB4EE1）。</summary>
    public const string ExtrudeSceneFeaturesJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/extrude_scene_features.schema.json",
         "title": "extrude_scene_features",
         "type": "object",
         "properties": {
          "layer": {
           "type": "string",
           "description": "图层名。"
          },
          "heightField": {
           "type": "string",
           "description": "高度字段（不改变真实几何源）。"
          },
          "unit": {
           "type": "string",
           "description": "高度单位。"
          },
          "missingPolicy": {
           "type": "string",
           "default": "skip",
           "description": "缺值政策。",
           "enum": [
            "skip",
            "zero",
            "error"
           ]
          },
          "negativePolicy": {
           "type": "string",
           "default": "reflect",
           "description": "负值政策。",
           "enum": [
            "reflect",
            "clamp",
            "error"
           ]
          }
         },
         "required": [
          "layer",
          "heightField",
          "unit"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X2",
          "catalogSection": "§4 X09",
          "overlapWithExisting": false,
          "rw": "S",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Layer",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string ExtrudeSceneFeaturesToolName = "extrude_scene_features";

    public const string ExtrudeSceneFeaturesSchemaSha256 = "BBF9E4BB4EE1D72F7F58CF4F156EE9B0C05CD2FF64519531092F9C172C798A79";

    public const string ExtrudeSceneFeaturesSchemaTextSha256 = "8E8ACB8A2454470192975C63FDC0927649B102846A8A2B75A23A087354CED8EB";

    /// <summary>create_elevation_profile · 冻结 schema 文本嵌入（正本原始 sha256 52E11BDB8A8D）。</summary>
    public const string CreateElevationProfileJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/create_elevation_profile.schema.json",
         "title": "create_elevation_profile",
         "type": "object",
         "properties": {
          "path": {
           "type": "string",
           "description": "剖面路径线要素。"
          },
          "surface": {
           "type": "string",
           "description": "高程面。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "sampleInterval": {
           "type": "number",
           "default": 0.0,
           "description": "抽样间隔（0＝按像元尺寸，须回显）。"
          },
          "zUnit": {
           "type": "string",
           "description": "Z 单位（显式）。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "path",
          "surface",
          "outputPath"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X2",
          "catalogSection": "§4 X12",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string CreateElevationProfileToolName = "create_elevation_profile";

    public const string CreateElevationProfileSchemaSha256 = "52E11BDB8A8D947A87D8B89FA56ABD3437056FBA59B21EC2A180634ECB88478C";

    public const string CreateElevationProfileSchemaTextSha256 = "3476364C6C6CE769107305C579240D50A7CE3D590890D7E4A97415CF22622FDC";

    /// <summary>export_scene_package · 冻结 schema 文本嵌入（正本原始 sha256 72F349A15954）。</summary>
    public const string ExportScenePackageJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/export_scene_package.schema.json",
         "title": "export_scene_package",
         "type": "object",
         "properties": {
          "scene": {
           "type": "string",
           "description": "场景名。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "includeTextures": {
           "type": "boolean",
           "default": true,
           "description": "是否包含纹理资源。"
          },
          "verifyReopen": {
           "type": "boolean",
           "default": true,
           "description": "是否执行离线重开校验（缺省 true）。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "scene",
          "outputPath"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X2",
          "catalogSection": "§4 X14",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Layout",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": "[VERIFY] 格式/资源边界经验证前不得声明支持（能力目录 §5 格式矩阵）。"
         }
        }
        """;

    public const string ExportScenePackageToolName = "export_scene_package";

    public const string ExportScenePackageSchemaSha256 = "72F349A15954549A2DD6B97D3928E71E6B329D4BFB52436F2E9269325FEACBD9";

    public const string ExportScenePackageSchemaTextSha256 = "5780D93DF0D3FD5C54F5327C39638F199962A4142BCD1580694CC387092FBD56";

    /// <summary>assess_remote_sensing_quality · 冻结 schema 文本嵌入（正本原始 sha256 AA8F0D52797D）。</summary>
    public const string AssessRemoteSensingQualityJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/assess_remote_sensing_quality.schema.json",
         "title": "assess_remote_sensing_quality",
         "type": "object",
         "properties": {
          "input": {
           "type": "string",
           "description": "影像或产品元数据。"
          },
          "sensorProfile": {
           "type": "string",
           "description": "传感器适配器 ID（省略 ⇒ 从元数据解析并回显；无法解析 ⇒ INVALID_ARGUMENT）。"
          },
          "unknownQaPolicy": {
           "type": "string",
           "default": "reject",
           "description": "未知 QA 编码政策。",
           "enum": [
            "reject",
            "report_only"
           ]
          }
         },
         "required": [
          "input"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X4",
          "catalogSection": "§4 X21",
          "overlapWithExisting": false,
          "rw": "R",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Quality",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": "R 若加报告落盘选项则按 W 检查（能力目录 §4 公共规则）。"
         }
        }
        """;

    public const string AssessRemoteSensingQualityToolName = "assess_remote_sensing_quality";

    public const string AssessRemoteSensingQualitySchemaSha256 = "AA8F0D52797DEF1B4308662FD64C813E13ECBF6C709DF443404A93F330B9168F";

    public const string AssessRemoteSensingQualitySchemaTextSha256 = "F49B0EAAB424672B0D9A6E04BF5419B522CC21EDEEE05859DF8ADAE4FEABB9B7";

    /// <summary>assess_classification_accuracy · 冻结 schema 文本嵌入（正本原始 sha256 432281952C0D）。</summary>
    public const string AssessClassificationAccuracyJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/assess_classification_accuracy.schema.json",
         "title": "assess_classification_accuracy",
         "type": "object",
         "properties": {
          "classified": {
           "type": "string",
           "description": "分类结果。"
          },
          "reference": {
           "type": "string",
           "description": "独立参考。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "samplingDesign": {
           "type": "string",
           "description": "抽样设计。",
           "enum": [
            "simple_random",
            "stratified",
            "systematic"
           ]
          },
          "computeInterval": {
           "type": "boolean",
           "default": true,
           "description": "是否计算条件允许的区间（不平衡须披露）。"
          },
          "seed": {
           "type": "integer",
           "default": 0,
           "description": "随机种子（缺省 0＝固定确定性种子）。0 表示“确定性默认”，不是“随机”。抽样/分类/聚类/情景/传播类工具必须可复现。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "classified",
          "reference",
          "outputPath",
          "samplingDesign"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X4",
          "catalogSection": "§4 X25",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Quality",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string AssessClassificationAccuracyToolName = "assess_classification_accuracy";

    public const string AssessClassificationAccuracySchemaSha256 = "432281952C0DAEBB72A145CC25F84374E083ECD61FE1B6925E9A7F1069F3A2E2";

    public const string AssessClassificationAccuracySchemaTextSha256 = "F572C286F58F7B1B0C1D2FF3C302217E7042EDE49B7BABA4CA202F067986EF56";

    /// <summary>design_spatial_sample · 冻结 schema 文本嵌入（正本原始 sha256 907D49FB6669）。</summary>
    public const string DesignSpatialSampleJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/design_spatial_sample.schema.json",
         "title": "design_spatial_sample",
         "type": "object",
         "properties": {
          "population": {
           "type": "string",
           "description": "抽样总体（面/栅格）。"
          },
          "strataField": {
           "type": "string",
           "description": "分层字段。"
          },
          "sampleSize": {
           "type": "integer",
           "description": "样本量（或按分层给）。"
          },
          "constraints": {
           "type": "object",
           "default": {},
           "description": "约束（最小间距/边界内缩/排除区）。"
          },
          "seed": {
           "type": "integer",
           "default": 0,
           "description": "随机种子（缺省 0＝固定确定性种子）。0 表示“确定性默认”，不是“随机”。抽样/分类/聚类/情景/传播类工具必须可复现。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "population",
          "sampleSize",
          "outputPath"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X5",
          "catalogSection": "§4 X29",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string DesignSpatialSampleToolName = "design_spatial_sample";

    public const string DesignSpatialSampleSchemaSha256 = "907D49FB6669CE63C4688157AAE525EB03242BE54C3D621B4C222DBDEB82C7CB";

    public const string DesignSpatialSampleSchemaTextSha256 = "4FD5ECAB1698A20B15A984146C5B5A3620C5D9CAE185175FB2D4247CC7280807";

    /// <summary>cross_validate_spatial_model · 冻结 schema 文本嵌入（正本原始 sha256 C074EA7012E3）。</summary>
    public const string CrossValidateSpatialModelJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/cross_validate_spatial_model.schema.json",
         "title": "cross_validate_spatial_model",
         "type": "object",
         "properties": {
          "observations": {
           "type": "string",
           "description": "观测数据。"
          },
          "modelSpec": {
           "type": "object",
           "description": "模型规格（方法+参数，不接受任意代码）。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "blocking": {
           "type": "string",
           "description": "空间分块方式。",
           "enum": [
            "random",
            "spatial_blocks",
            "leave_one_out"
           ]
          },
          "folds": {
           "type": "integer",
           "default": 5,
           "description": "折数。"
          },
          "seed": {
           "type": "integer",
           "default": 0,
           "description": "随机种子（缺省 0＝固定确定性种子）。0 表示“确定性默认”，不是“随机”。抽样/分类/聚类/情景/传播类工具必须可复现。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "observations",
          "modelSpec",
          "outputPath",
          "blocking"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X5",
          "catalogSection": "§4 X31",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": "[VERIFY] 空间泄漏检查须给出可核对证据。"
         }
        }
        """;

    public const string CrossValidateSpatialModelToolName = "cross_validate_spatial_model";

    public const string CrossValidateSpatialModelSchemaSha256 = "C074EA7012E359FDFCA94A033CFE9E07DDF668F81647F3D8C583A11C0C458558";

    public const string CrossValidateSpatialModelSchemaTextSha256 = "7734E84D52E2A02D26ADA5999F2DAEE129C0E52D55C7BE0702C7918ABFDE03D7";

    /// <summary>analyze_scenario_sensitivity · 冻结 schema 文本嵌入（正本原始 sha256 B760DE0F4AB0）。</summary>
    public const string AnalyzeScenarioSensitivityJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/analyze_scenario_sensitivity.schema.json",
         "title": "analyze_scenario_sensitivity",
         "type": "object",
         "properties": {
          "parameters": {
           "type": "object",
           "description": "明确参数域（每参数的区间/离散集）。"
          },
          "scenarios": {
           "type": "array",
           "description": "情景集合（或生成规则）。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "maxSolves": {
           "type": "integer",
           "default": 200,
           "description": "求解次数预算上限。"
          },
          "seed": {
           "type": "integer",
           "default": 0,
           "description": "随机种子（缺省 0＝固定确定性种子）。0 表示“确定性默认”，不是“随机”。抽样/分类/聚类/情景/传播类工具必须可复现。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "parameters",
          "scenarios",
          "outputPath"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X5",
          "catalogSection": "§4 X32",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": "扰动不冒充概率（能力目录 §4 X32）。"
         }
        }
        """;

    public const string AnalyzeScenarioSensitivityToolName = "analyze_scenario_sensitivity";

    public const string AnalyzeScenarioSensitivitySchemaSha256 = "B760DE0F4AB023646204C0E30D8E94AFA7FF6D9645373698EF0A34F3A04FF784";

    public const string AnalyzeScenarioSensitivitySchemaTextSha256 = "CD249B9DCFDB11A154CB3D70F1BC3288789626E1242A3485BBFD28EC35A19938";

    /// <summary>compare_multi_criteria_scenarios · 冻结 schema 文本嵌入（正本原始 sha256 985310BD18DA）。</summary>
    public const string CompareMultiCriteriaScenariosJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/compare_multi_criteria_scenarios.schema.json",
         "title": "compare_multi_criteria_scenarios",
         "type": "object",
         "properties": {
          "alternatives": {
           "type": "string",
           "description": "备选方案（要素或表）。"
          },
          "criteria": {
           "type": "array",
           "description": "指标清单（字段/方向/归一化）。"
          },
          "weights": {
           "type": "object",
           "description": "权重（必须显式给出；不得由 AI 偷定）。"
          },
          "constraints": {
           "type": "array",
           "default": [],
           "description": "硬约束（独立于评分）。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "alternatives",
          "criteria",
          "weights",
          "outputPath"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X5",
          "catalogSection": "§4 X34",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string CompareMultiCriteriaScenariosToolName = "compare_multi_criteria_scenarios";

    public const string CompareMultiCriteriaScenariosSchemaSha256 = "985310BD18DA7C0628E1DBA17AA9E702C85761872546766A8C94545874F87025";

    public const string CompareMultiCriteriaScenariosSchemaTextSha256 = "39F1C2D3B250C41E3C4247F0DB56457E567C9B963188A150CA70E4E186E56281";

    /// <summary>evaluate_scenario_ensemble · 冻结 schema 文本嵌入（正本原始 sha256 7D40C9D2FE3E）。</summary>
    public const string EvaluateScenarioEnsembleJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/evaluate_scenario_ensemble.schema.json",
         "title": "evaluate_scenario_ensemble",
         "type": "object",
         "properties": {
          "ensemble": {
           "type": "array",
           "description": "有限情景集合。"
          },
          "weights": {
           "type": "object",
           "default": {},
           "description": "可选权重（须依据充分；否则只称情景分布）。"
          },
          "outputPath": {
           "type": "string",
           "description": "输出绝对路径（D 盘工作根内）。经路径守卫；落在受保护根 ⇒ PATH_ESCAPE_REJECTED。"
          },
          "disagreementThreshold": {
           "type": "number",
           "default": 0.0,
           "description": "分歧区阈值。"
          },
          "overwrite": {
           "type": "boolean",
           "default": false,
           "description": "允许覆盖已存在的输出。默认 false：输出已存在且未显式 overwrite=true ⇒ OUTPUT_EXISTS，不执行任何写。",
           "note": "现役复用点 OverwritePolicy.SchemaProperty（Source/Shared/ArcGISProMCP.Core/Results/OverwritePolicy.cs:40）；其 description 目前把默认值写在**文本**里而非 schema 的 default 键 ⇒ O-D080-04 待归并项。"
          }
         },
         "required": [
          "ensemble",
          "outputPath"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X5",
          "catalogSection": "§4 X35",
          "overlapWithExisting": false,
          "rw": "W",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Analysis",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string EvaluateScenarioEnsembleToolName = "evaluate_scenario_ensemble";

    public const string EvaluateScenarioEnsembleSchemaSha256 = "7D40C9D2FE3E256D178A26DAC56D655B0C447538654C1A46F75AD33A7840DAC8";

    public const string EvaluateScenarioEnsembleSchemaTextSha256 = "B33D36025A29E576692B54E9FEF61CA83BF310F0BCA800334BAC96DB7F490999";

    /// <summary>validate_statistical_assumptions · 冻结 schema 文本嵌入（正本原始 sha256 BD3CF2A0A148）。</summary>
    public const string ValidateStatisticalAssumptionsJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/validate_statistical_assumptions.schema.json",
         "title": "validate_statistical_assumptions",
         "type": "object",
         "properties": {
          "variables": {
           "type": "array",
           "description": "变量清单（字段+角色）。"
          },
          "design": {
           "type": "object",
           "description": "设计信息（抽样/空间结构）。"
          },
          "intendedMethod": {
           "type": "string",
           "description": "拟用方法 ID（须在有限目录内；否则返回 unknown 而非 applicable）。"
          },
          "checks": {
           "type": "array",
           "default": [
            "normality",
            "independence",
            "stationarity",
            "heteroscedasticity"
           ],
           "description": "检验目录。"
          }
         },
         "required": [
          "variables",
          "intendedMethod"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X5",
          "catalogSection": "§4 X36",
          "overlapWithExisting": false,
          "rw": "R",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Quality",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": ""
         }
        }
        """;

    public const string ValidateStatisticalAssumptionsToolName = "validate_statistical_assumptions";

    public const string ValidateStatisticalAssumptionsSchemaSha256 = "BD3CF2A0A148DF7DACFA20B81A7C9EED08646763064654A7691032A961EF1367";

    public const string ValidateStatisticalAssumptionsSchemaTextSha256 = "D8277F27F35B688CE117CD9D1198F39A90DFF566E5FC49CA58F3DEEB740390C3";

    /// <summary>validate_interchange_conformance · 冻结 schema 文本嵌入（正本原始 sha256 D8819CE3E755）。</summary>
    public const string ValidateInterchangeConformanceJson =
        """
        {
         "$schema": "https://json-schema.org/draft/2020-12/schema",
         "$id": "arcgis-pro-mcp/candidate/validate_interchange_conformance.schema.json",
         "title": "validate_interchange_conformance",
         "type": "object",
         "properties": {
          "input": {
           "type": "string",
           "description": "文件路径。"
          },
          "standardVersion": {
           "type": "string",
           "description": "标准/版本（如 GeoPackage 1.3 / GeoParquet 1.0）。"
          },
          "deepChecks": {
           "type": "array",
           "default": [
            "schema",
            "crs",
            "axis_order",
            "geometry_types",
            "precision"
           ],
           "description": "检查目录。"
          },
          "reportPath": {
           "type": "string",
           "description": "可选：结构化报告落盘绝对路径。一旦提供，该工具按 W（写）检查：路径守卫 + OUTPUT_EXISTS 闸门 + 产物进 ArtifactManifest。未提供则只返回内存结果。"
          }
         },
         "required": [
          "input",
          "standardVersion"
         ],
         "additionalProperties": false,
         "x-d082": {
          "status": "PENDING F03-a adjudication",
          "batch": "X7",
          "catalogSection": "§4 X43",
          "overlapWithExisting": false,
          "rw": "R",
          "requiresArcGIS": true,
          "executionType": "Native",
          "category": "Quality",
          "pythonBridge": false,
          "psDependent": false,
          "hold": null,
          "note": "[VERIFY] 格式适配范围与标准版本未真实试验（能力目录 §5）。"
         }
        }
        """;

    public const string ValidateInterchangeConformanceToolName = "validate_interchange_conformance";

    public const string ValidateInterchangeConformanceSchemaSha256 = "D8819CE3E755C110CA8F504A3EC3D0AB2852A7900D0EF7A1A2794BD21431DE1C";

    public const string ValidateInterchangeConformanceSchemaTextSha256 = "269FD24C3EDA66F99EE011D9187743312C15FEE02C46E2918F9DF2E1C8F037A6";
    /// <summary>工具名 → 冻结 schema 嵌入文本（顺序＝工单范围逐字序）。</summary>
    public static readonly IReadOnlyDictionary<string, string> ByToolName =
        new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            [DetectTemporalChangePointsToolName] = DetectTemporalChangePointsJson,
            [CompareTemporalTrajectoriesToolName] = CompareTemporalTrajectoriesJson,
            [ExportTimeAnimationToolName] = ExportTimeAnimationJson,
            [ExtrudeSceneFeaturesToolName] = ExtrudeSceneFeaturesJson,
            [CreateElevationProfileToolName] = CreateElevationProfileJson,
            [ExportScenePackageToolName] = ExportScenePackageJson,
            [AssessRemoteSensingQualityToolName] = AssessRemoteSensingQualityJson,
            [AssessClassificationAccuracyToolName] = AssessClassificationAccuracyJson,
            [DesignSpatialSampleToolName] = DesignSpatialSampleJson,
            [CrossValidateSpatialModelToolName] = CrossValidateSpatialModelJson,
            [AnalyzeScenarioSensitivityToolName] = AnalyzeScenarioSensitivityJson,
            [CompareMultiCriteriaScenariosToolName] = CompareMultiCriteriaScenariosJson,
            [EvaluateScenarioEnsembleToolName] = EvaluateScenarioEnsembleJson,
            [ValidateStatisticalAssumptionsToolName] = ValidateStatisticalAssumptionsJson,
            [ValidateInterchangeConformanceToolName] = ValidateInterchangeConformanceJson,
        };

    /// <summary>工具名 → 冻结 schema 正本原始字节 SHA-256（大写；逐件 ≡ surface 登记值）。</summary>
    public static readonly IReadOnlyDictionary<string, string> SchemaSha256ByToolName =
        new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            [DetectTemporalChangePointsToolName] = DetectTemporalChangePointsSchemaSha256,
            [CompareTemporalTrajectoriesToolName] = CompareTemporalTrajectoriesSchemaSha256,
            [ExportTimeAnimationToolName] = ExportTimeAnimationSchemaSha256,
            [ExtrudeSceneFeaturesToolName] = ExtrudeSceneFeaturesSchemaSha256,
            [CreateElevationProfileToolName] = CreateElevationProfileSchemaSha256,
            [ExportScenePackageToolName] = ExportScenePackageSchemaSha256,
            [AssessRemoteSensingQualityToolName] = AssessRemoteSensingQualitySchemaSha256,
            [AssessClassificationAccuracyToolName] = AssessClassificationAccuracySchemaSha256,
            [DesignSpatialSampleToolName] = DesignSpatialSampleSchemaSha256,
            [CrossValidateSpatialModelToolName] = CrossValidateSpatialModelSchemaSha256,
            [AnalyzeScenarioSensitivityToolName] = AnalyzeScenarioSensitivitySchemaSha256,
            [CompareMultiCriteriaScenariosToolName] = CompareMultiCriteriaScenariosSchemaSha256,
            [EvaluateScenarioEnsembleToolName] = EvaluateScenarioEnsembleSchemaSha256,
            [ValidateStatisticalAssumptionsToolName] = ValidateStatisticalAssumptionsSchemaSha256,
            [ValidateInterchangeConformanceToolName] = ValidateInterchangeConformanceSchemaSha256,
        };

    /// <summary>工具名 → 嵌入文本（正本 CRLF→LF 归一后）的 SHA-256。</summary>
    public static readonly IReadOnlyDictionary<string, string> SchemaTextSha256ByToolName =
        new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            [DetectTemporalChangePointsToolName] = DetectTemporalChangePointsSchemaTextSha256,
            [CompareTemporalTrajectoriesToolName] = CompareTemporalTrajectoriesSchemaTextSha256,
            [ExportTimeAnimationToolName] = ExportTimeAnimationSchemaTextSha256,
            [ExtrudeSceneFeaturesToolName] = ExtrudeSceneFeaturesSchemaTextSha256,
            [CreateElevationProfileToolName] = CreateElevationProfileSchemaTextSha256,
            [ExportScenePackageToolName] = ExportScenePackageSchemaTextSha256,
            [AssessRemoteSensingQualityToolName] = AssessRemoteSensingQualitySchemaTextSha256,
            [AssessClassificationAccuracyToolName] = AssessClassificationAccuracySchemaTextSha256,
            [DesignSpatialSampleToolName] = DesignSpatialSampleSchemaTextSha256,
            [CrossValidateSpatialModelToolName] = CrossValidateSpatialModelSchemaTextSha256,
            [AnalyzeScenarioSensitivityToolName] = AnalyzeScenarioSensitivitySchemaTextSha256,
            [CompareMultiCriteriaScenariosToolName] = CompareMultiCriteriaScenariosSchemaTextSha256,
            [EvaluateScenarioEnsembleToolName] = EvaluateScenarioEnsembleSchemaTextSha256,
            [ValidateStatisticalAssumptionsToolName] = ValidateStatisticalAssumptionsSchemaTextSha256,
            [ValidateInterchangeConformanceToolName] = ValidateInterchangeConformanceSchemaTextSha256,
        };
}
